//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Verarbeitung
{
	using EingabeAusgabe;
	using ErrorHandling;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Aenderung
	{
		public virtual Polynom Polynom
		{
			get;
			set;
		}

		public virtual bool IsNachfrage
		{
			get;
			set;
		}

		public virtual int Wert
		{
			get;
			set;
		}

		public virtual double Zeitpunkt
		{
			get;
			set;
		}

		public Aenderung(Polynom polynom, bool isNachfrage, int wer, double zeitpunkt)
		{
		}

		public virtual string ToString()
		{
			throw new System.NotImplementedException();
		}

	}
}

