//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Verarbeitung
{
	using EingabeAusgabe;
	using ErrorHandling;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Bedarf
	{
		public virtual List<Aenderung> Daten
		{
			get;
			set;
		}

		public virtual Polynom Angebot
		{
			get;
			set;
		}

		public virtual Polynom Nachfrage
		{
			get;
			set;
		}

		public Bedarf(Polynom angebot, Polynom nachfrage, double genauigkeit)
		{
		}

		private Nullable<double> FindeNST(Polynom polynom, double genauigkeit)
		{
			throw new System.NotImplementedException();
		}

		private Nullable<double> Bisektion(double a, double b, Polynom polynom)
		{
			throw new System.NotImplementedException();
		}

		public virtual int BeraechneMaxBedarf()
		{
			throw new System.NotImplementedException();
		}

		private void BeraechneDaten(Polynom polynom, bool isNachfrage)
		{
			throw new System.NotImplementedException();
		}

		public virtual double Get(double x)
		{
			throw new System.NotImplementedException();
		}

	}
}

