//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Program
{
	using EingabeAusgabe;
	using Fehlerbehandung;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Verarbeitung;

	public class Program
	{
		public static void Main(string[] args)
		{
			throw new System.NotImplementedException();
		}

	}
}

