//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace IO
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FileInputReader : IReader
	{
		public virtual string FilePath
		{
			get;
			set;
		}

		public virtual void InputReader(string path)
		{
			throw new System.NotImplementedException();
		}

		public virtual InputData Read()
		{
			throw new System.NotImplementedException();
		}

		private InputData CeateInputData(List<string> lines)
		{
			throw new System.NotImplementedException();
		}

	}
}

