//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace IO
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FileOutputWriter : IWriter
	{
		public virtual string FilePath
		{
			get;
			set;
		}

		public virtual void OutputWriter(string path)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Write(OutputData data)
		{
			throw new System.NotImplementedException();
		}

		private string GenerateText(OutputData data)
		{
			throw new System.NotImplementedException();
		}

	}
}

