//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Verarbeitung {
    using EingabeAusgabe;
    using Fehlerbehandung;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Aenderung {
        public virtual Polynom Polynom {
            get;
            set;
        }
        public virtual bool IsNachfrage {
            get;
            set;
        }
        public virtual int Wert {
            get;
            set;
        }
        public virtual double Zeitpunkt {
            get;
            set;
        }
        public virtual int PosX {
            get;
            private set;
        }
        public virtual int PosY {
            get;
            private set;
        }

        public Aenderung(Polynom polynom, bool isNachfrage, int wert, double zeitpunkt, int posX, int posY) {
            PosX = posX;
            PosY = posY;
            Polynom = polynom;
            IsNachfrage = isNachfrage;
            Wert = wert;
            Zeitpunkt = zeitpunkt;
        }
        
        public override string ToString() {
            var aktion = IsNachfrage ? "Nachfrage" : "Abstellung";
            return $"{aktion} in Q_{PosX+1}{PosY+1} zu t={Math.Round(Zeitpunkt,2)}";
        }

    }
}

