//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Verarbeitung {
    using EingabeAusgabe;
    using Fehlerbehandung;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Aenderung {
        public virtual Polynom Polynom {
            get;
            set;
        }

        public virtual bool IsNachfrage {
            get;
            set;
        }

        public virtual int Wert {
            get;
            set;
        }

        public virtual double Zeitpunkt {
            get;
            set;
        }

        public Aenderung(Polynom polynom, bool isNachfrage, int wert, double zeitpunkt) {
            Polynom = polynom;
            IsNachfrage = isNachfrage;
            Wert = wert;
            Zeitpunkt = zeitpunkt;
        }

        public virtual string ToString(int x, int y) {
            var aktion = IsNachfrage ? "Nachfrage" : "Abstellung";
            return $"{aktion} in Q_{x}{y} zu t={Zeitpunkt}";
        }
        public override string ToString() {
            var aktion = IsNachfrage ? "Nachfrage" : "Abstellung";
            return $"{aktion} in Q_?? zu t={Zeitpunkt}";
        }

    }
}

