//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Verarbeitung {
    using EingabeAusgabe;
    using Fehlerbehandung;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Bedarf {
        public virtual List<Aenderung> Daten {
            get;
            private set;
        }

        public virtual Polynom Angebot {
            get;
            private set;
        }

        public virtual Polynom Nachfrage {
            get;
            private set;
        }
        public virtual double Genauigkeit {
            get;
            private set;
        }

        public Bedarf(Polynom angebot, Polynom nachfrage, double genauigkeit) {
            Daten = new List<Aenderung>();
            angebot = Angebot;
            nachfrage = Nachfrage;
            Genauigkeit = genauigkeit;
            BeraechneDaten(angebot, false);
            BeraechneDaten(nachfrage, true);
        }

        private Nullable<double> FindeNST(Polynom polynom, double genauigkeit) {
            throw new System.NotImplementedException();
        }

        private Nullable<double> Bisektion(double a, double b, Polynom polynom) {
            throw new System.NotImplementedException();
        }

        public virtual int BeraechneMaxBedarf() {
            throw new System.NotImplementedException();
        }

        private void BeraechneDaten(Polynom polynom, bool isNachfrage) {
            throw new System.NotImplementedException();
        }

        public virtual double Get(double x) {
            throw new System.NotImplementedException();
        }

    }
}

