//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Program {
    using EingabeAusgabe;
    using Fehlerbehandung;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Verarbeitung;

    public class Program {
        public static void Main(string[] args) {
            if (args.Count() == 0) {
                args = new string[] { // nur zum Debuggen
                    @"..\..\..\..\..\Input\1.in",
                    @"..\..\..\..\..\Output\1.out",
                    "0.0001",
                };
            }
            var leser = new DateiEinlesen(args[0]);
            var daten = leser.Lesen();

            var ausgabe = new AusgabeDaten(daten);
            ausgabe.Simulationsverlauf.Add("Abstellung in Q_11 zu t=2,30");
            ausgabe.Simulationsverlauf.Add("Nachfrage in Q_11 zu t=3,76");
            ausgabe.Maximalbedarf[0, 0] = 1;
            ausgabe.Endzustand[0, 0] = 0;
            var schreiber = new DateiSchreiben(args[1]);
            schreiber.Schreiben(ausgabe);

            Console.ReadKey();
        }

    }
}

