//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace IO {
    using ErrorHandling;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;

    public class FileInputReader : IReader {
        public virtual string FilePath {
            get;
            set;
        }

        public IReader IReader {
            get {
                throw new System.NotImplementedException();
            }

            set {
            }
        }

        public FileInputReader(string path) {
            FilePath = path;
        }

        public virtual InputData Read() {
            if (!File.Exists(FilePath))
                throw new IHKException("File dose not exist");
            var lines = File.ReadAllLines(FilePath);
            List<string> validLines = (from item in lines
                             where string.IsNullOrWhiteSpace(item)
                             select item).ToList();
            return CeateInputData(validLines);
        }

        private InputData CeateInputData(List<string> lines) {
            var inputData = new InputData();
            foreach (var line in lines) {
                // do something with inputData
            }
            return inputData;
        }

    }
}

