//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace IO {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;

    public class FileOutputWriter : IWriter {
        public virtual string FilePath {
            get;
            set;
        }

        public IWriter IWriter {
            get {
                throw new System.NotImplementedException();
            }

            set {
            }
        }

        public FileOutputWriter(string path) {
            FilePath = path;
        }

        public virtual void Write(OutputData data) {
            string text = GenerateText(data);
            File.WriteAllText(FilePath,text);
        }

        private string GenerateText(OutputData data) {
            return "some text\n...";
        }
    }
}

