//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace EingabeAusgabe
{
	using ErrorHandling;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Verarbeitung;

	public class AusgabeDaten
	{
		public virtual EingabeDaten InputData
		{
			get;
			set;
		}

		public virtual List<string> Simulationsverlauf
		{
			get;
			set;
		}

		public virtual int Endzustand
		{
			get;
			set;
		}

		public virtual int Maximalbedarf
		{
			get;
			set;
		}

		public AusgabeDaten(EingabeDaten inputData)
		{
		}

		public virtual string GeneriereText()
		{
			throw new System.NotImplementedException();
		}

	}
}

