//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace EingabeAusgabe
{
	using Fehlerbehandung;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Verarbeitung;

	public class DateiEinlesen : ILeser
	{
		private string Dateipfad
		{
			get;
			set;
		}

		public DateiEinlesen(string path)
		{
		}

		public virtual EingabeDaten Lesen()
		{
			throw new System.NotImplementedException();
		}

		private Polynom GetPolynom(string str)
		{
			throw new System.NotImplementedException();
		}

	}
}

