.TH "C:/Users/Readock/Documents/Git/IHK2017/SourceCode/CarsharingSimulator/CarsharingSimulator/EingabeAusgabe/AusgabeDaten.cs" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Readock/Documents/Git/IHK2017/SourceCode/CarsharingSimulator/CarsharingSimulator/EingabeAusgabe/AusgabeDaten.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEingabeAusgabe\&.AusgabeDaten\fP"
.br
.RI "Klasse welche Informationen zur berrechneten Lösung der Simulation haelt "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEingabeAusgabe\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
