.TH "C:/Users/Readock/Documents/Git/IHK2017/SourceCode/CarsharingSimulator/CarsharingSimulator/EingabeAusgabe Directory Reference" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Readock/Documents/Git/IHK2017/SourceCode/CarsharingSimulator/CarsharingSimulator/EingabeAusgabe Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAusgabeDaten\&.cs\fP"
.br
.ti -1c
.RI "file \fBDateiEinlesen\&.cs\fP"
.br
.ti -1c
.RI "file \fBDateiSchreiben\&.cs\fP"
.br
.ti -1c
.RI "file \fBEingabeDaten\&.cs\fP"
.br
.ti -1c
.RI "file \fBILeser\&.cs\fP"
.br
.ti -1c
.RI "file \fBISchreiber\&.cs\fP"
.br
.in -1c
