.TH "EingabeAusgabe.ILeser" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EingabeAusgabe.ILeser \- Interface fuer das Lesen von Daten  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEingabeAusgabe\&.DateiEinlesen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEingabeDaten\fP \fBLesen\fP ()"
.br
.RI "Liest Daten ein "
.in -1c
.SH "Detailed Description"
.PP 
Interface fuer das Lesen von Daten 


.SH "Member Function Documentation"
.PP 
.SS "\fBEingabeDaten\fP EingabeAusgabe\&.ILeser\&.Lesen ()"

.PP
Liest Daten ein 
.PP
\fBReturns:\fP
.RS 4
Daten
.RE
.PP

.PP
Implemented in \fBEingabeAusgabe\&.DateiEinlesen\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
