.TH "EingabeAusgabe.DateiSchreiben" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EingabeAusgabe.DateiSchreiben \- Klasse welche das schreiben von \fBAusgabeDaten\fP in eine Datei ermoeglicht  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEingabeAusgabe\&.ISchreiber\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDateiSchreiben\fP (string path)"
.br
.RI "Konstruktor "
.ti -1c
.RI "virtual void \fBSchreiben\fP (\fBAusgabeDaten\fP data)"
.br
.RI "Schreibt die Daten in eine Datei "
.in -1c
.SH "Detailed Description"
.PP 
Klasse welche das schreiben von \fBAusgabeDaten\fP in eine Datei ermoeglicht 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "EingabeAusgabe\&.DateiSchreiben\&.DateiSchreiben (string path)"

.PP
Konstruktor 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Dateipfad
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual void EingabeAusgabe\&.DateiSchreiben\&.Schreiben (\fBAusgabeDaten\fP data)\fC [virtual]\fP"

.PP
Schreibt die Daten in eine Datei 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Daten
.RE
.PP

.PP
Implements \fBEingabeAusgabe\&.ISchreiber\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
