.TH "EingabeAusgabe.ISchreiber" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EingabeAusgabe.ISchreiber \- Interface zum Schreiben von Daten  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEingabeAusgabe\&.DateiSchreiben\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSchreiben\fP (\fBAusgabeDaten\fP data)"
.br
.RI "Schreibt Daten "
.in -1c
.SH "Detailed Description"
.PP 
Interface zum Schreiben von Daten 


.SH "Member Function Documentation"
.PP 
.SS "void EingabeAusgabe\&.ISchreiber\&.Schreiben (\fBAusgabeDaten\fP data)"

.PP
Schreibt Daten 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Daten
.RE
.PP

.PP
Implemented in \fBEingabeAusgabe\&.DateiSchreiben\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
