.TH "EingabeAusgabe" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EingabeAusgabe
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAusgabeDaten\fP"
.br
.RI "Klasse welche Informationen zur berrechneten Lösung der Simulation haelt "
.ti -1c
.RI "class \fBDateiEinlesen\fP"
.br
.RI "Klasse welche das Einlesen von \fBEingabeDaten\fP aus einer Datei ermoeglicht "
.ti -1c
.RI "class \fBDateiSchreiben\fP"
.br
.RI "Klasse welche das schreiben von \fBAusgabeDaten\fP in eine Datei ermoeglicht "
.ti -1c
.RI "class \fBEingabeDaten\fP"
.br
.RI "Klasse welche daten Enthaelt die fuer eine Simulation benoetigt werden "
.ti -1c
.RI "interface \fBILeser\fP"
.br
.RI "Interface fuer das Lesen von Daten "
.ti -1c
.RI "interface \fBISchreiber\fP"
.br
.RI "Interface zum Schreiben von Daten "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
