.TH "EingabeAusgabe.DateiEinlesen" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EingabeAusgabe.DateiEinlesen \- Klasse welche das Einlesen von \fBEingabeDaten\fP aus einer Datei ermoeglicht  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEingabeAusgabe\&.ILeser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDateiEinlesen\fP (string pfad)"
.br
.RI "Konstruktor "
.ti -1c
.RI "virtual \fBEingabeDaten\fP \fBLesen\fP ()"
.br
.RI "Liest die \fBEingabeDaten\fP aus der angegebenen Datei ein "
.in -1c
.SH "Detailed Description"
.PP 
Klasse welche das Einlesen von \fBEingabeDaten\fP aus einer Datei ermoeglicht 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "EingabeAusgabe\&.DateiEinlesen\&.DateiEinlesen (string pfad)"

.PP
Konstruktor 
.PP
\fBParameters:\fP
.RS 4
\fIpfad\fP Dateipfad
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBEingabeDaten\fP EingabeAusgabe\&.DateiEinlesen\&.Lesen ()\fC [virtual]\fP"

.PP
Liest die \fBEingabeDaten\fP aus der angegebenen Datei ein 
.PP
\fBReturns:\fP
.RS 4
Daten
.RE
.PP

.PP
Implements \fBEingabeAusgabe\&.ILeser\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
