.TH "EingabeAusgabe.EingabeDaten" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EingabeAusgabe.EingabeDaten \- Klasse welche daten Enthaelt die fuer eine Simulation benoetigt werden  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEingabeDaten\fP (int m)"
.br
.RI "Konstruktor "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBM\fP\fC [get, set]\fP"
.br
.RI "Dimension der Simulierten Quadrate (insgesamt M*M Quadrate) "
.ti -1c
.RI "virtual \fBPolynom\fP [,] \fBAngebotVerteilung\fP\fC [get, set]\fP"
.br
.RI "Angebotsverteilungen fuer jedes Quadrat "
.ti -1c
.RI "virtual \fBPolynom\fP [,] \fBNachfrageVerteilung\fP\fC [get, set]\fP"
.br
.RI "NachfrageVerteilungen fuer jedes Quadrat "
.ti -1c
.RI "virtual string \fBKopfzeile\fP\fC [get, set]\fP"
.br
.RI "Kopfzeile "
.in -1c
.SH "Detailed Description"
.PP 
Klasse welche daten Enthaelt die fuer eine Simulation benoetigt werden 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "EingabeAusgabe\&.EingabeDaten\&.EingabeDaten (int m)"

.PP
Konstruktor 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "virtual \fBPolynom\fP [,] EingabeAusgabe\&.EingabeDaten\&.AngebotVerteilung\fC [get]\fP, \fC [set]\fP"

.PP
Angebotsverteilungen fuer jedes Quadrat 
.SS "virtual string EingabeAusgabe\&.EingabeDaten\&.Kopfzeile\fC [get]\fP, \fC [set]\fP"

.PP
Kopfzeile 
.SS "virtual int EingabeAusgabe\&.EingabeDaten\&.M\fC [get]\fP, \fC [set]\fP"

.PP
Dimension der Simulierten Quadrate (insgesamt M*M Quadrate) 
.SS "virtual \fBPolynom\fP [,] EingabeAusgabe\&.EingabeDaten\&.NachfrageVerteilung\fC [get]\fP, \fC [set]\fP"

.PP
NachfrageVerteilungen fuer jedes Quadrat 

.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
