.TH "Fehlerbehandung" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fehlerbehandung
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIHKException\fP"
.br
.RI "Exception welche eine Fehlermeldung auf der Konsole ausgibt und das Programm dann beendet "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
