.TH "Fehlerbehandung.IHKException" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fehlerbehandung.IHKException \- Exception welche eine Fehlermeldung auf der Konsole ausgibt und das Programm dann beendet  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIHKException\fP (string message)"
.br
.RI "Konstruktor "
.in -1c
.SH "Detailed Description"
.PP 
Exception welche eine Fehlermeldung auf der Konsole ausgibt und das Programm dann beendet 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fehlerbehandung\&.IHKException\&.IHKException (string message)"

.PP
Konstruktor 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP Fehlernachricht
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
