.TH "C:/Users/Readock/Documents/Git/IHK2017/SourceCode/CarsharingSimulator/CarsharingSimulator/Fehlerbehandung/IHKException.cs" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Readock/Documents/Git/IHK2017/SourceCode/CarsharingSimulator/CarsharingSimulator/Fehlerbehandung/IHKException.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFehlerbehandung\&.IHKException\fP"
.br
.RI "Exception welche eine Fehlermeldung auf der Konsole ausgibt und das Programm dann beendet "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFehlerbehandung\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
