.TH "Program.Program" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Program.Program \- Klasse welche die Main Methode beinhaltet  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP (string[] args)"
.br
.RI "Main Methode die das Programm steuert "
.in -1c
.SH "Detailed Description"
.PP 
Klasse welche die Main Methode beinhaltet 


.SH "Member Function Documentation"
.PP 
.SS "static void Program\&.Program\&.Main (string [] args)\fC [static]\fP"

.PP
Main Methode die das Programm steuert 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
