.TH "Verarbeitung" 3 "Thu May 18 2017" "CarsharingSimulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Verarbeitung
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAenderung\fP"
.br
.RI "KLasse welche eine \fBAenderung\fP in der Bedarfsfunktion darstellt "
.ti -1c
.RI "class \fBBedarf\fP"
.br
.RI "Bedarfsfunktion welche den \fBBedarf\fP an Autos auf eine Position beschreibt "
.ti -1c
.RI "class \fBPolynom\fP"
.br
.RI "Klasse welche ein \fBPolynom\fP Repraesentiert "
.ti -1c
.RI "class \fBSimulation\fP"
.br
.RI "Klasse welche die \fBSimulation\fP ausfuert "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CarsharingSimulator from the source code\&.
