//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace EingabeAusgabe {
    using Fehlerbehandung;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Verarbeitung;

    public class AusgabeDaten {
        public virtual EingabeDaten InputData {
            get;
            set;
        }

        public virtual List<string> Simulationsverlauf {
            get;
            set;
        }

        public virtual int[,] Endzustand {
            get;
            set;
        }

        public virtual int[,] Maximalbedarf {
            get;
            set;
        }

        public AusgabeDaten(EingabeDaten inputData) {
            InputData = inputData;
            Simulationsverlauf = new List<string>();
            Endzustand = new int[InputData.M, InputData.M];
            Maximalbedarf = new int[InputData.M, InputData.M];
        }

        public virtual string GeneriereText() {
            // Kommentarzeile
            var text = InputData.Kopfzeile + Environment.NewLine;
            // Historie
            foreach (var item in Simulationsverlauf)
                text += item + Environment.NewLine;
            // Endzustand
            text += "# Endzustand des Tages:" + Environment.NewLine;
            for (int i = 0; i < Endzustand.GetLength(1); i++) {
                for (int j = 0; j < Endzustand.GetLength(0); j++) 
                    text += Endzustand[i, j] + " ";                
                text += Environment.NewLine;
            }
            // Maximalbedarf
            text += "# Maximaler Bedarf:" + Environment.NewLine;
            for (int i = 0; i < Maximalbedarf.GetLength(1); i++) {
                for (int j = 0; j < Maximalbedarf.GetLength(0); j++) 
                    text += Maximalbedarf[i, j] + " ";                
                text += Environment.NewLine;
            }
            return text;
        }

    }
}

