//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace EingabeAusgabe {
    using Fehlerbehandung;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Verarbeitung;

    public class EingabeDaten {
        public virtual int M {
            get;
            set;
        }

        public virtual Polynom[,] AngebotVerteilung {
            get;
            set;
        }

        public virtual Polynom[,] NachfrageVerteilung {
            get;
            set;
        }

        public virtual string Kopfzeile {
            get;
            set;
        }

        public EingabeDaten(int m) {
            M = m;
            AngebotVerteilung = new Polynom[m, m];
            NachfrageVerteilung = new Polynom[m, m];
            Kopfzeile = "";
        }

    }
}

